language: java
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8
  - openjdk8

after_success:
  - mvn clean cobertura:cobertura coveralls:cobertura

sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.m2
